services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoppro
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shoppro"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

# In your docker-compose.yml file...
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo 'Ensuring database schema is up to date...' &&
        npx prisma migrate deploy &&
        echo 'Attempting to seed database directly...' &&
        npx ts-node prisma/seed.ts &&
        echo 'Seeding complete. Starting application...' &&
        node dist/main
      "


  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    environment:
      # Replace the placeholder with your actual VPS IP address
      - VITE_API_BASE_URL=http://172.237.149.11:3000
    command: npm run dev
    depends_on:
      - backend
volumes:
  db-data:
